### ISSUE TITLE
(400) Bad Request

### ISSUE THREAD

**Issue by vikashdaya** [gabrielsroka/OktaAPI.psm1#1]
I followed your instructions but still get the following error when trying to use these.

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Program Files\WindowsPowerShell\Modules\OktaAPI\1.0.5\OktaAPI.psm1:118 char:5
+     Invoke-RestMethod $url -Method $method -Headers $headers -Body $j ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by gabrielsroka** [comment]
It works for me. Can you send more of your code? Exclude the API token.

Also, installing Fiddler can be helpful.

**Comment by vikashdaya** [comment]
It works now... I had to look inside the OktaAPI.psm1 file to work out how to use the New-OktaGroup cmdlet (which you kindly provided in a comment before the function).  It's not a simple case of calling the cmdlet and prividing a group name.  There's a profile construct being used which wasn't very obvious. Might be worth documenting these commands in one place or build in some help/examples into the cmdlets.

**Comment by gabrielsroka** [comment]
OK. There is also sample code in the CallOktaAPI.ps1 file.
