### ISSUE TITLE
Get-OktaUserGroups doesn't support paginated return

### ISSUE THREAD

**Issue by cci-konmal** [gabrielsroka/OktaAPI.psm1#10]
Get-OktaUserGroups doesn't support paginated return. If a user is a member of more than 200 groups, only first 200 hundred are being returned.

**Comment by gabrielsroka** [comment]
Hi @km-cci 

Sorry about that. here's a fix. i'll publish it here in GitHub and on powershellgallery.com asap:

in OktaAPI.psm1 (or in your own file), change (or add) the existing function to:
```powershell
function Get-OktaUserGroups($id, $limit = 200, $url = "/api/v1/users/$id/groups?limit=$limit", $paged = $false) {
    if ($paged) {
        Invoke-PagedMethod $url
    } else {
        Invoke-Method GET $url
    }
}
```

Then restart PowerShell.

to call it:
```powershell
$id = "00u4i04zqt4TW0h7"

$params = @{id = $id; paged = $true}
do {
    $page = Get-OktaUserGroups @params
    $groups = $page.objects
    foreach ($group in $groups) {
        Write-Host $group.id
    }
    $params = @{url = $page.nextUrl; paged = $true}
} while ($page.nextUrl)
```

**Comment by gabrielsroka** [comment]
i pushed the code to github and to powershellgallery (v. 1.0.19):
https://www.powershellgallery.com/packages/OktaAPI

i'm going to close this issue. if it doesn't work, please reopen.

thanks.
