### ISSUE TITLE
License

### ISSUE THREAD

**Issue by natescherer** [gabrielsroka/OktaAPI.psm1#11]
Hello,
Would you mind adding a license to this project? I'm interested in possibly forking it but wanted to be clear on the licensing before I did. Thanks!

**Comment by gabrielsroka** [comment]
Hi @natescherer 
I've thought about this, and even started researching different licenses, but I haven't really figured it out yet.

In essence, you can do whatever you want with the code. Attribution would be nice. The code is offered without warranty.

Would you be interested in submitting PRs back to this repo? Or is this for private use?

Thanks,

Gabriel

**Comment by natescherer** [comment]
I'd definitely be willing to submit PRs if you're open to it. If it ends up spinning off into its own thing, too, I will naturally give you attribution. Love the rockstar plugin, btw.

**Comment by gabrielsroka** [comment]
Thanks and thanks!
