### ISSUE TITLE
Invoke-RestMethod 400 Bad Request

### ISSUE THREAD

**Issue by MDFogle** [gabrielsroka/OktaAPI.psm1#12]
So, I'm attempting to modify an Okta user with the Set-OktaUser command, but it keeps giving an error message when I attempt to Set the changes back to the system.  I feel like I'm missing something obvious, but what might it be?

Thanks!!!

PS C:\Windows\system32> $user.profile

firstName   : Testing
lastName    : BettyWhite
mobilePhone : 4992387489725
secondEmail : --------------------------------
login       : ------------------------------------
email       : 

PS C:\Windows\system32> $user.profile.mobilePhone = "4995551234"

PS C:\Windows\system32> Set-OktaUser $user
Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Program Files\WindowsPowerShell\Modules\OktaAPI\1.0.19\OktaAPI.psm1:283 char:5
+     Invoke-RestMethod $url -Method $method -Headers $headers -Body $j ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by gabrielsroka** [comment]
hi @MDFogle 

`Set-OktaUser` requires an ID and a user object, so try:
```powershell
Set-OktaUser $user.id $user
```

see also example:
https://github.com/gabrielsroka/OktaAPI.psm1/blob/master/CallOktaAPI.ps1#L428-L440

actual module source code:
https://github.com/gabrielsroka/OktaAPI.psm1/blob/master/Modules/OktaAPI.psm1#L221-L224

you can also get help from PowerShell, eg:
![image](https://user-images.githubusercontent.com/14354736/96194477-4dd22880-0eff-11eb-8850-113499c8c8bb.png)

I also recommend using Fiddler to debug issues like this. there's some info in the README

and say hi to Betty for me!
