### ISSUE TITLE
Bulk import into Okta

### ISSUE THREAD

**Issue by srirao28** [gabrielsroka/OktaAPI.psm1#17]
file - users.csv
``` csv
login,email,firstName,lastName,password,groupid
pwsh5@gmail.com,pwsh5@gmail.com,user5,pwsh,Password1!,xxxxxyyyzzz
```

steps followed:
``` powershell
Import-Module OktaAPI
Connect-Okta "<API Token>" "https://tenant.okta.com"
Import-Users users.csv
```

Results:
user got created in the correct groupID mentioned in csv
status on user - marked as below
  Staged
  Activate

![user_record_marked_as_activate_okta](https://user-images.githubusercontent.com/78626222/107130538-61354500-689c-11eb-8dd5-732f3c8b47ec.png)

how to auto-activate users when doing a bulk (CSV) import
    What should be the header parameter in my csv file to accomplish this.

Cannot login into okta console with newly created login / password.
Looks like password given in csv file is not properly assigned to the user record during import.

Any help is highly appreciated !

**Comment by gabrielsroka** [comment]
@srirao28 
`Import-Users` calls `New-OktaUser` which is:
https://github.com/gabrielsroka/OktaAPI.psm1/blob/master/Modules/OktaAPI.psm1#L240-L242

**Comment by srirao28** [comment]
Thank you for the comments !

Could you please elaborate a little more on how to achieve my above two tasks.

**Comment by gabrielsroka** [comment]
@srirao28 

As I wrote in the readme file, this module assumes you're familiar with the Okta API. 

For example:
https://developer.okta.com/docs/reference/api/users/#create-user-with-password

**Comment by srirao28** [comment]
Great, 

I am a begginer to powershell and so finding it difficult to consume all the pointers you are helping me with.

For now, configured a virtual box and trying to figure out by running every cmdlet you created in your module.

Will spend time to obsorb the concepts. Thank you for so much for your time !!

**Comment by gabrielsroka** [comment]
You're welcome.

If you noticed, `Import-Users` doesn't actually mention passwords anywhere, but there are other examples in the same file that do. If you combine the pieces together, you can probably do what you need. For example:

``` powershell
function Import-UsersWithPassword() {
<# Sample users.csv file. Make sure you include the header line as the first record.
login,email,firstName,lastName,password,groupId
testa1@okta.com,testa1@okta.com,Test,A1,password1,00g5gtwaaeOe7smEF0h7
testa2@okta.com,testa2@okta.com,Test,A2,password2,00g5gtwaaeOe7smEF0h7
#>
    $users = Import-Csv users.csv
    $importedUsers = @()
    foreach ($user in $users) {
        $newUser = @{
            profile = @{
                login = $user.login
                email = $user.email
                firstName = $user.firstName
                lastName = $user.lastName
            }
            credentials = @{
                password = @{
                    value = $user.password
                }
            }
            groupIds = @($user.groupId)
        }
        $message = ""
        try {
            $oktaUser = New-OktaUser $newUser $true
        } catch {
            try {
                $oktaUser = Get-OktaUser $user.login
            } catch {
                $oktaUser = $null
                $message = "Invalid user."
            }
        }
        $importedUsers += [PSCustomObject]@{id = $oktaUser.id; login = $user.login; message = $message}
    }
    $importedUsers | Export-Csv importedUsers.csv -NoTypeInformation
    "$($users.count) users read."
}
```

**Comment by srirao28** [comment]
wow !!

This is really awesome and nice of you !!

I will save above contents to a file with extension .ps1 and run it for myself on my virtualbox.

Will keep you informed on my outcomes, thank you again so much !!

**Comment by gabrielsroka** [comment]
You're welcome. 

May I ask why you're running virtualbox? PowerShell runs on Windows, mac and Linux (see my readme for more info).

**Comment by srirao28** [comment]
Sure !!

I am using my work laptop, it does have PowerShell, but it has a rule that blocks me from executing any scripts. So, had to set up VBox/CentOS, configure PowerShell and trigger the script from there.

**Comment by gabrielsroka** [comment]
I see. It makes sense that it might be locked down.

Did you look at:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7.1

**Comment by srirao28** [comment]
Thank you for the reference document !!

I will surely review and see if that works for me.

**Comment by gabrielsroka** [comment]
hi @srirao28 

i'm following up. did this work for you? if so, please close this issue (or i'll do it in a few days).

you can always reopen it if necessary.

thanks.

**Comment by srirao28** [comment]
Sorry for the delay. Yes, this did work for me, this is great !

QQ - any inputs on the best approach to create groups in okta via csv file.

When to use below snippet ?
```powershell
# Create a group.
$profile = @{name = $name; description = $description}
$group = New-OktaGroup @{profile = $profile}
```

** planning to follow below steps:
1) add below function to file and name it as importgroups.ps1
2) prepare csv file with required group name & description.
3) trigger the ps1 script

```powershell
# Read groups from CSV and create them in Okta.
function New-Groups() {
<# Sample groups.csv file with 2 fields. Make sure you include the header line as the first record.
name,description
PowerShell Group,Members of this group are awesome.
#>
    $groups = Import-Csv groups.csv
    $importedGroups = @()
    foreach ($group in $groups) {
        $profile = @{name = $group.name; description = $group.description}
        try {
            $oktaGroup = New-OktaGroup @{profile = $profile}                   # <---- SEE HERE
            $message = "New group"
        } catch {
            Get-Error $_
            try {
                $oktaGroup = Get-OktaGroups $group.name 'type eq "OKTA_GROUP"'
                $message = "Found group"
            } catch {
                Get-Error $_
                $oktaGroup = $null
                $message = "Invalid group"
            }
        }
        $importedGroups += [PSCustomObject]@{id = $oktaGroup.id; name = $group.name; message = $message}
    }
    $importedGroups | Export-Csv importedGroups.csv -notype
    "$($groups.count) groups read." 
}
```

Any inputs appreciated !!

**Comment by gabrielsroka** [comment]
the 3-line snippet is just an example of how to use `New-OktaGroup` by itself. 

the `New-Groups` function already calls `New-OktaGroup`, in a loop, with other stuff (it's about the 12th line in the function).

here's a shorter, simpler version without error checking that might be easier to understand. see line 10 (`SEE HERE`)
```powershell
function New-GroupsNoErrorChecking() {
<# Sample groups.csv file with 2 fields. Make sure you include the header line as the first record.
name,description
PowerShell Group,Members of this group are awesome.
#>
    $groups = Import-Csv groups.csv
    $importedGroups = @()
    foreach ($group in $groups) {
        $profile = @{name = $group.name; description = $group.description}
        $oktaGroup = New-OktaGroup @{profile = $profile}                             # <----- SEE HERE
        $importedGroups += [PSCustomObject]@{id = $oktaGroup.id; name = $group.name}
    }
    $importedGroups | Export-Csv importedGroups.csv -notype
    "$($groups.count) groups read." 
}
```

**Comment by srirao28** [comment]
Nice explanation, Thank you for all your time !!

I will run it for myself and see how things works for me and share my further thoughts..

**Comment by srirao28** [comment]
Update: 

Unfortunately, your script is not working for me. Looks like I messed up something.. 

---contents of csv file- groups.csv
name, group description
cog-readonly, read only group - cognos
cog-admins, admin group - cognos
cog-sit, sit environment group - cognos


--- contents of ./New-Groups.ps1
```powershell
#import the OktaAPI module
Import-Module OktaAPI
#Connect-Okta "<API Token>" "https://tenant.okta.com"

#function New-Groups() {
function New-Groups($csvPath){

# Sample groups.csv file with 2 fields. Make sure you include the header line as the first record.
# name,description
# PowerShell Group,Members of this group are awesome.
#
#    $groups = Import-Csv groups.csv
     $groups = Import-Csv $csvPath
    $importedGroups = @()
    foreach ($group in $groups) {
        $profile = @{name = $group.name; description = $group.description}
        try {
            $oktaGroup = New-OktaGroup @{profile = $profile}                   # <---- SEE HERE
            $message = "New group"
        } catch {
            Get-Error $_
            try {
                $oktaGroup = Get-OktaGroups $group.name 'type eq "OKTA_GROUP"'
                $message = "Found group"
            } catch {
                Get-Error $_
                $oktaGroup = $null
                $message = "Invalid group"
            }
        }
        $importedGroups += [PSCustomObject]@{id = $oktaGroup.id; name = $group.name; message = $message}
    }
    $importedGroups | Export-Csv importedGroups.csv -notype
    "$($groups.count) groups read." 
}
```

any suggestions appreciated !!

**Comment by gabrielsroka** [comment]
the header line in csv has to match the code that reads the CSV:
```
# Sample groups.csv file with 2 fields. Make sure you include the header line as the first record.
# name,description
# PowerShell Group,Members of this group are awesome.
```

has to match this
```
        $profile = @{name = $group.name; description = $group.description}
```

your file is using `group description`. change it to `description` and see if it works better.

**Comment by srirao28** [comment]
Thank you for your email and details !!

I did update the input file as per your recommendations. But, still no
luck, will continue to get a full understanding of the logic....

-- contents of groups.csv
name,description
cogreadonly, read only group cognos
cogadmins, admin group cognos
cogsit, sit environment group cognos
cogqa, qa environment group cognos


Was checking in Okta GUI under 'Add Group' to see what fields are listed
while creating a group. I see only two as you mentioned.
name and description

[image: image.png]


Also I will spend time to get some kind of error messages once i trigger
the script that way it will help to troubleshoot exact cause...

Will keep you posted with more findings to take guidance from your
expertise !

Thank you !!
Sri



#import the OktaAPI module
Import-Module OktaAPI

#Connect-Okta "<API Token>" "https://tenant.okta.com"
Connect-Okta "<xxxxxxxxxxxxxxxxx>" "https://xxyyzzaabbccdd.okta.com"

#function New-Groups() {

function New-Groups($csvPath) {

   # Sample groups.csv file with 2 fields. Make sure you include the header
line as the first record.
   #name,description
   #PowerShell Group,Members of this group are awesome.
   #
#   $groups = Import-Csv groups.csv

  $groups = Import-Csv $csvPath
    $importedGroups = @()
    foreach ($group in $groups) {
        $profile = @{name = $group.name; description = $group.description}
        try {
            $oktaGroup = New-OktaGroup @{profile = $profile}
   # <---- SEE HERE
            $message = "New group"
        } catch {
            Get-Error $_
            try {
                $oktaGroup = Get-OktaGroups $group.name 'type eq
"OKTA_GROUP"'
                $message = "Found group"
            } catch {
                Get-Error $_
                $oktaGroup = $null
                $message = "Invalid group"
            }
        }

$importedGroups += [PSCustomObject]@{id = $oktaGroup.id; name = $group.name;
message = $message}
    }
    $importedGroups | Export-Csv importedGroups.csv -notype
    "$($groups.count) groups read."
}

**Comment by gabrielsroka** [comment]
You said "it's not working". I would need more information in order to help you.

Are getting an error? If so, what is it? Is it doing anything? Are you calling the `New-Groups` function? You've defined it, but I don't see where you're calling it. Is there more code?

**Comment by srirao28** [comment]
Thank you for the follow up !!

Your questions had an hidden answer for me. I called the function within
the script and now I am able to see the groups in my okta tenant.

You are the best !

[image: image.png]

[image: image.png]

[image: image.png]

**Comment by srirao28** [comment]
Need your expertise on the below..

I have group - cogprod already in my tenant. Trying to understand what does
the script do if a group already exists.. any advice to deal with this ?


PS /home/powershell/Scripts> ./New-Groups.ps1 ./groups.csv
Creating group for cogprod
InvalidOperation:
/root/.local/share/powershell/Modules/OktaAPI/1.0.19/OktaAPI.psm1:325
Line |
 325 |      $responseStream = $_.Exception.Response.GetResponseStream()
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Method invocation failed because
[System.Net.Http.HttpResponseMessage] does not contain a method
     | named 'GetResponseStream'.

1 groups read.

**Comment by gabrielsroka** [comment]
It looks like `Get-Error` code no longer works. in Windows PowerShell 5, i get nothing. In PowerShell 6/7, I get an error.

I don't have time to fix this now.

I suggest you re-write the code. Here are two approaches:
1. if you get an error, just continue, or
2. search for the group. If it exists, skip it. If it doesn't exist, import it. this is slower than approach 1, but won't create errors

Unless you're finding other problems with my module, I'm going to close this issue. If you need additional help writing your code, I'm available at an hourly rate.

**Comment by srirao28** [comment]
Good to know. Thank you for all the inputs and help !

I am also running version 7. Will spend time on internet to see if I can
get this fixed.

PS /home/powershell/Scripts> pwsh -v
PowerShell 7.1.1

**Comment by srirao28** [comment]
Hello,

I am newbie with programming / okta.

Could you please help me with a few pointers on below.

1) what would be an ideal way to ACTIVATE users in bulk in okta.

2) Assign users to a group in bulk

your inputs highly appreciated.

Thanks!
Sri

**Comment by gabrielsroka** [comment]
https://github.com/gabrielsroka/OktaAPI.psm1/blob/71f1dacb680af1121026d5ae657ca2874b484213/Modules/OktaAPI.psm1#L269-L271

https://github.com/gabrielsroka/OktaAPI.psm1/blob/71f1dacb680af1121026d5ae657ca2874b484213/Modules/OktaAPI.psm1#L179-L181

There are no bulk operations in the API as far as I know. You can check the documentation. Otherwise you'll have to call these functions in a loop.

**Comment by gabrielsroka** [comment]
See also 
https://github.com/gabrielsroka/OktaAPI.psm1/blob/71f1dacb680af1121026d5ae657ca2874b484213/CallOktaAPI.ps1#L314-L347
