### ISSUE TITLE
Get-OktaUser Exception thrown ??

### ISSUE THREAD

**Issue by citnadxela** [gabrielsroka/OktaAPI.psm1#2]
Everytime I try to get a user, being prompted wi/ the following error:

Get-OktaUser : Exception of type 'Okta.Core.OktaException' was thrown.
At line:1 char:9
 $user = Get-OktaUser "user"
         ~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (:) [Get-OktaUser], OktaException
     FullyQualifiedErrorId : Okta.Core.OktaException,Okta.Core.Automation.GetOktaUser

**Comment by gabrielsroka** [comment]
Hi @citnadxela 
It looks like you're trying to open an issue with the Official Okta PowerShell code. That repo is here:
https://github.com/okta/okta-sdk-dotnet/tree/legacy/Okta.Core.Automation

Note that it's considered Legacy. I'm not sure what kind of support you might get on it, but I'm sure it can't hurt to try.

See also
https://github.com/okta/okta-sdk-dotnet/tree/legacy/Okta.Core.Automation#troubleshooting

Also, installing Fiddler can be helpful.

If you like, try using my, unofficial code and see if it works.

**Comment by citnadxela** [comment]
Apologies.  I'm not quite sure how to get started.  I've ran:

Install-Module OktaAPI

Then, when I try to connect to my environment, get prompted wi/:

Connect-Okta "YOUR_API_TOKEN" "https://YOUR_ORG.oktapreview.com"

Unable to find type [Runtime.InteropServices.RuntimeInformation].
At C:\Program Files\WindowsPowerShell\Modules\OktaAPI\1.0.12\OktaAPI.psm1:17 char:15
     $osDesc = [Runtime.InteropServices.RuntimeInformation]::OSDescrip ...
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidOperation: (Runtime.Interop...timeInformation:TypeName) [], RuntimeException
     FullyQualifiedErrorId : TypeNotFound

**Comment by gabrielsroka** [comment]
Hmm. What version of PowerShell are you using? You can check `$PSVersionTable`

**Comment by citnadxela** [comment]
I think I got everything working.  I cloned the repo instead of downloading & started over.  Apologies again.

**Comment by gabrielsroka** [comment]
Me too, it works for me. 

Does this work?
`[system.Runtime.InteropServices.RuntimeInformation]::OSDescription`

**Comment by citnadxela** [comment]
I think I got everything working. I cloned the repo instead of downloading & started over. Apologies again.

**Comment by gabrielsroka** [comment]
Glad to hear it.
