### ISSUE TITLE
Query : What is $group ? OktaAPI.psm1/Modules/OktaAPI.psm1 : Line 82

### ISSUE THREAD

**Issue by pm-bhatt** [gabrielsroka/OktaAPI.psm1#20]
Hi @gabrielsroka 

I am not sure if this is the right forum to ask the query, hence apologise if this should not be placed here

I am trying to add a group to an app via Okta API in PowerShell using the OKTA API

I am using the function below from the code of OKTA-API.psm1, line 82
```
function Add-OktaAppGroup($appid, $groupid, $group) 
{
    Invoke-Method PUT "/api/v1/apps/$appid/groups/$groupid" $group
}
```
I am not sure what value I should be passing to $groups because, in OKTA-API for assigning app to the group, it only requires groupID and appID - {{url}}/api/v1/apps/appid/groups/groupid

Let me know if I should provide more inputs for this.

**Comment by gabrielsroka** [comment]
You can assign the `priority`, or leave it blank. see the response for an example
https://developer.okta.com/docs/reference/api/apps/#response-example-34
```
Add-OktaAppGroup $appid $groupid
# or, set the priority
Add-OktaAppGroup $appid $groupid @{priority = 6}
```

**Comment by gabrielsroka** [comment]
You can also use it to set group properties. eg, when I assign a group to Salesforce (with provisioning enabled), the group can have these properties (and more). If you get the group info first, you'll see what I mean.

```
Add-OktaAppGroup $appid $groupid @{profile = @{street = 'Main'; city = 'LA' ...}}
```

![image](https://user-images.githubusercontent.com/14354736/127359631-b35083d7-2589-444a-a63e-e72ccf691ece.png)

**Comment by pm-bhatt** [comment]
Thanks @gabrielsroka for your help :-)
