### ISSUE TITLE
Query - New Group Rules

### ISSUE THREAD

**Issue by SCAJohnV** [gabrielsroka/OktaAPI.psm1#21]
I'm trying to better understand how to new group rules with New-OktaGroupRule, but I'm afraid I just can't get the syntax correct.

Would you mind posting a working example of how you would construct the parameters for New-OktaGroupRule?

Below is my current attempt at this command.

``` powershell
New-OktaGroupRule @{
type = "group_rule"
name = "TestGroup01Rule"
conditions = @{
    value = "user.ej_location==\00000000\"
    type = "urn:oktaexpresssion:1.0"
actions = @{
    assignUserToGroups =@{
        groupIds = "GroupIDhere"
        allGroupsValid = "$True"

    }
```

**Comment by gabrielsroka** [comment]
an example
https://developer.okta.com/docs/reference/api/groups/#create-group-rule

steps to convert JSON to PowerShell
https://github.com/gabrielsroka/OktaAPI.psm1#converting-json-to-powershell

**Comment by SCAJohnV** [comment]
I've actually been trying to follow the API reference doc from Okta that you linked.
Would you mind pasting a sample of what it would look like in Powershell?
I'm having trouble figuring out where I'm messing up.

**Comment by gabrielsroka** [comment]
Would you share what you've done so far?

**Comment by SCAJohnV** [comment]
Sure.

```powershell
$value = 'user.ej_location==\"00000000\"'

New-OktaGroupRule @{
type = "group_rule"
name = "TestGroup01Rule"
conditions = @{
        people = @{
            users = @{
                Exclude = ""
        }}}

        groups = @{
exclude = ""

        }

        expression = @{  
    value = $value
    type = "urn:oktaexpresssion:1.0"    
    }
actions = @{
    assignUserToGroups =@{
        groupIds = @("00g3jzw6uzmhL2ykt297")
        

}
}
}
```

**Comment by gabrielsroka** [comment]
here's a functioning (tho not useful) example

btw, you can use triple backticks in GitHub to quote your code

```powershell
$newRule = ConvertFrom-Json @"
{
  "type": "group_rule",
  "name": "A PS rule",
  "conditions": {
    "expression": {
      "value": "user.login == Engineer",
      "type": "urn:okta:expression:1.0"
    }
  },
  "actions": {
    "assignUserToGroups": {
      "groupIds": [
        "00g10usgcxtVV5CYe0h8"
      ]
    }
  }
}
"@

New-OktaGroupRule $newRule
```

**Comment by gabrielsroka** [comment]
note that JSON is case-sensitive. if Okta wants `exclude`, then `Exclude` won't work

**Comment by gabrielsroka** [comment]
also, the `type` in your example is incorrrect

**Comment by gabrielsroka** [comment]
this example is a little more like yours (you had also misspelled `expression`)

i find the indentation to be very helpful

```powershell
$value = 'user.login == "abc"'

New-OktaGroupRule @{
    type = "group_rule"
    name = "a ps rule"
    conditions = @{
        people = @{
            users = @{
                exclude = @()
            }
            groups = @{
                exclude = @()
            }
        }
        expression = @{  
            value = $value
            type = "urn:okta:expression:1.0"    
        }
    }
    actions = @{
        assignUserToGroups = @{
            groupIds = @("00g3jzw6uzmhL2ykt297")
        }
    }
}
```

**Comment by SCAJohnV** [comment]
Ahhh - Both of your most recent responses with code have been incredibly helpful. I thank you.
