### ISSUE TITLE
Import existing users to single group via CSV?

### ISSUE THREAD

**Issue by joelglynn1** [gabrielsroka/OktaAPI.psm1#29]
Hello! Apologies somewhat new to both GitHub and PowerShell. 

Question - trying to take the snipping below, but for my situation I want to take a CSV of _existing users_, and assign them all to a single existing Okta group. I've tried modifying this in various ways but keeps failing. I have (2) columns in my CSV, one for username and one for the group ID, but cannot get this to run correctly. Any recommendations?

```PowerShell
function Import-UsersAndGroups() {
<# Sample CSV file with 5 fields. Make sure you include the header line as the first record.
login,email,firstName,lastName,groupIds
testa1@okta.com,testa1@okta.com,Test,A1,"00g5gtwaaeOe7smEF0h7;00g5gtwaaeOe7smFF0h7"
testa2@okta.com,testa2@okta.com,Test,A2,"00g5gtwaaeOe7smEF0h7;00g5gtwaaeOe7smFF0h7"
#>
    $users = Import-Csv usersAndGroups.csv
    foreach ($user in $users) {
        $profile = @{login = $user.login; email = $user.email; firstName = $user.firstName; lastName = $user.lastName}
        $groupIds = $user.groupIds -split ";"
        $oktaUser = New-OktaUser @{profile = $profile; groupIds = $groupIds}
    }
}
```

Tried something along these lines, a few different ways but I feel like its missing the command to 'add to group' or something like that:

```posh
$users = Import-Csv 
foreach ($user in $users) {
        $login = $user.login
        $groupIds = $user.groupIds
    }
```

Thank you!
Joel

**Comment by gabrielsroka** [comment]
This function is probably what you need, but notice it needs a userID, not a username, so you will need another function to figure that out.

`Add-OktaGroupMember $groupid $userid`

https://github.com/gabrielsroka/OktaAPI.psm1/blob/c99d7f4fc62d9bc3dfefcd1079f72f68cf0cb05f/Modules/OktaAPI.psm1#L179-L181

`Get-OktaUser $username` Will accept a userID or a username and return the full user object that includes the userID.

https://github.com/gabrielsroka/OktaAPI.psm1/blob/c99d7f4fc62d9bc3dfefcd1079f72f68cf0cb05f/Modules/OktaAPI.psm1#L244-L246

See 

https://github.com/gabrielsroka/OktaAPI.psm1/blob/c99d7f4fc62d9bc3dfefcd1079f72f68cf0cb05f/CallOktaAPI.ps1#L213-L217

**Comment by srirao28** [comment]
Experts, I am newbie to powershell / okta functions.
user and group - existing in okta
user - alpha_userId
group - group1id, group2id, group3id etc

Assign One user to 10 different groups

Contents of my CSV:
```csv
userID, groupID
alpha_userId,group1id
alpha_userId,group2id
alpha_userId,group3id
```

Contents of my PS1 script:
```powershell
Import-Module OktaAPI
Connect-Okta "xyzabc" "https://abcXYZ_oktapriview.com/"
function Add-GroupMember() {
  $users = Import-Csv existingusers.csv
  foreach ($user in $users) {
    $user = Get-OktaUser "loginID"
    # $group = Get-OktaGroups "PowerShell" 'type eq "OKTA_GROUP"'
    Add-OktaGroupMember $group.id $user.id
  }
}
Add-GroupMember existingusers.csv
```

Trying various ways, one of the way mentioned above, any inputs / pointers on what is that I am missing.
Appreciated !

**Comment by gabrielsroka** [comment]
It's difficult to read your code that way. Can you reformat it with triple back quotes ``` like this?

Indentation helps too.

````
```powershell
$lines = Import-Csv existingusers.csv
foreach ($line in $lines) {
    Add-OktaGroupMember $line.groupID $line.userID
}
```
````

**Comment by srirao28** [comment]
contents of my PS1 script:

```powershell
Import-Module OktaAPI
Connect-Okta "xyzabc" "https://abcXYZ_oktapriview.com/"
function Add-GroupMember() {
  $users = Import-Csv existingusers.csv
  foreach ($user in $users) {
    $user = Get-OktaUser "loginID"
    Add-OktaGroupMember $group.id $user.id 
  }
}
Add-GroupMember existingusers.csv
```

**Comment by gabrielsroka** [comment]
Triple back quotes: ```
Use them before and after. Or Google it

**Comment by srirao28** [comment]
Sorry for the trouble. Hope now it looks good. thank you for time


```powershell
Import-Module OktaAPI
Connect-Okta "xyzabc" "https://abcXYZ_oktapriview.com/"
function Add-GroupMember() {
  $users = Import-Csv existingusers.csv
  foreach ($user in $users) {
    $user = Get-OktaUser "loginID"
    Add-OktaGroupMember $group.id $user.id
  }
}
Add-GroupMember existingusers.csv
```

**Comment by gabrielsroka** [comment]
I haven't tested it.

```pwsh
$lines = Import-Csv existingusers.csv
foreach ($line in $lines) {
    $user = Get-OktaUser $line.userID
    Add-OktaGroupMember $line.groupID $user.id
}
```

**Comment by gabrielsroka** [comment]
If the CSV already has the user id

```pwsh
$lines = Import-Csv existingusers.csv
foreach ($line in $lines) {
    Add-OktaGroupMember $line.groupID $line.userID
}
```

**Comment by srirao28** [comment]
thank you so much for the feedback
I will test these and share my findings..

**Comment by srirao28** [comment]
Experts, 

Trying to map application & group

applicationID - abcd
groupID - xyzg
group name - admins

appId_groupId.csv - contents
applicationID,groupID,group
abcd,xyzg,admins

```pwsh
Import-Module OktaAPI
Connect-Okta "xyzabc" "https://abcXYZ_okta.com/"
function Add-AppAssign() {
  $lines = Import-Csv appId_groupId.csv
  foreach ($line in $lines) {
    Add-OktaAppGroup $line.applicationId $line.groupId $line.group
  }
}
Add-AppAssign appId_groupId.csv
```

Error:
Invoke-RestMethod: {"errorCode":"E0000003","errorSummary":"The request body was not well-formed."


Inputs appreciated !

**Comment by gabrielsroka** [comment]
> Experts

there's only me. no one else.


the 3rd argument to `Add-OktaAppGroup` expects a group object/hash, just like https://developer.okta.com/docs/reference/api/apps/#assign-group-to-application

so maybe
```powershell
Add-OktaAppGroup $line.applicationId $line.groupId @{}
```

~but i haven't tested it.~

**Comment by gabrielsroka** [comment]
i tested it. it works, you can also omit that last argument, so

```
Add-OktaAppGroup $line.applicationId $line.groupId
```

please don't reuse existing/closed issues. open a new one in this repo.

**Comment by srirao28** [comment]
Thank you so much

I added the last argument and now i see 

error: Invoke-RestMethod: {"errorCode":"E0000006","errorSummary":"You do not have permission to perform the
requested action"

Right now have my Token name is having a role- Org Admin

Any idea what should be the role in okta

inputs appreciated as always

**Comment by srirao28** [comment]
Ah okay, I actually opened a new issue.. 

https://github.com/gabrielsroka/OktaAPI.psm1/issues/32
Map existing application and group in okta gabrielsroka/OktaAPI.psm1#32

sorry for the trouble

**Comment by gabrielsroka** [comment]
the other repo is the wrong repo. use this repo for PowerShell.

i don't know what the role should be. try it with Super Admin, if it works, then check the documentation.

**Comment by srirao28** [comment]
Ahh got it.

I will open a new issue in this repo itself, thank you for the details.

**Comment by gabrielsroka** [comment]
note that this was covered in https://github.com/gabrielsroka/OktaAPI.psm1/issues/20

please check existing issues before creating new ones.
