### ISSUE TITLE
Using bearer tokens in Connect-Okta

### ISSUE THREAD

**Issue by AristidesStamatiou** [gabrielsroka/OktaAPI.psm1#31]
Hi Gabriel,

I'm using your API to do a host of different functions for a client. I've coded everything up and it was working perfectly, thank you so much for the API! 

However, since I don't want my client to have the API key hardcoded in the script, I set up a device grant flow to get a bearer access token for making calls to the API. I've modified the Connect-Okta functions Authorization Header to use the "Bearer " header to access the Okta API with the proper key. When testing this in Postman, it should be working. However when I then try to use this Connect-Okta function with the script it's giving me "Invalid URI: The hostname could not be parsed" errors. 

Would you by any chance know how to use the device grant flow with your API?

**Comment by gabrielsroka** [comment]
No. Doesn't it need a private key?

**Comment by AristidesStamatiou** [comment]
No, a private key isn't necessary. 

Would you know what could cause the script to throw the invalid URI message? I'm using the same url as I would normally. In Postman it works, I've only changed the Content type and the Authorization headers for the Connect-Okta step. I just can't seem to figure out why this error keeps popping up, is there a way to check the current hostname?

**Comment by gabrielsroka** [comment]
How do you do it in Postman? Can you send me the actual error or the code? What are the Okta docs for this?

**Comment by gabrielsroka** [comment]
The project readme file mentions Fiddler. Did you try it?

**Comment by AristidesStamatiou** [comment]
In postman it works, I just follow the Device Flow Grant. The flow is described here: https://developer.okta.com/docs/guides/device-authorization-grant/main/#request-access-id-and-refresh-tokens

**Comment by AristidesStamatiou** [comment]
I've downloaded Fiddler and when going through the flow, I can see all the requests and responses. They all follow my expectations. After receiving the access_token I make my first call with the API. I get the response I've mentioned before but see no outgoing requests in Fiddler.

**Comment by AristidesStamatiou** [comment]
I think what my question would be is the following:
Is it possible to modify the Connect-Okta function to work with the following two headers:
"Authorization" = "Bearer $($bearer_access_token)"
"Content-Type" = "application/x-www-form-urlencoded"

Or is there anything that I'm currently not seeing that would prevent the Connect-Okta function from executing properly? And especially something that would then result in the "Invalid URI: The hostname could not be parsed" error?

I could send you my code if you'd like but the only thing that I've changed is what I mentioned above. Using the Get-OktaGroups function already throws an error, whilst I am able to follow my device code grant flow in Postman and then, using the headers as mentioned above, get a list of all the groups.

**Comment by gabrielsroka** [comment]
Changing the content type would not be a good idea and is probably not necessary either. 

As I asked earlier, send me all your code without tokens and I can take a look.

**Comment by AristidesStamatiou** [comment]
Hi Gabriel, thanks for the response. I ended up writing my own functions for the API calls to fix the issue, so no assistance is required.

**Comment by gabrielsroka** [comment]
Do you mind sharing your solution in case others are interested?
