### ISSUE TITLE
Getting next page of logs

### ISSUE THREAD

**Issue by daviscraigs** [gabrielsroka/OktaAPI.psm1#4]
Hi Gabriel,

I'm new to using APIs and am working on a PowerShell script to automate the download of Okta system logs. I have Get-OktaLogs working and am able to capture the numbers of log entries based on the -limit value. My understanding is I should be able to then pull the next page of logs. How would I get the next page of logs?

Thank you,
Craig

**Comment by gabrielsroka** [comment]
@daviscraigs
Hi Craig
Check out the [readme](../blob/master/README.md). It has a link to pagination:
https://developer.okta.com/docs/api/getting_started/design_principles#pagination

I have sample code that might help:
https://github.com/gabrielsroka/OktaAPI.psm1/blob/master/CallOktaAPI.ps1#L192-L237

See also:
https://github.com/mbegan/Okta-Scripts/blob/master/saveEventLogs.md
