### ISSUE TITLE
New-OktaGroup 

### ISSUE THREAD

**Issue by nate-meir** [gabrielsroka/OktaAPI.psm1#7]
New-OktaGroup doesn't work properly. The only command that gives me trouble
![image](https://user-images.githubusercontent.com/42188649/60744895-38690300-9f35-11e9-8a99-62322b513822.png)

**Comment by nate-meir** [comment]
Modifying your function for it seemed to do the trick

```powershell
function New-OktaGroup($group, $description) {
    $profile = @{
          profile = @{
            name = "$group"
            description = "$description"
        }
    }
    Invoke-Method POST "/api/v1/groups" $profile
}
```

**Comment by gabrielsroka** [comment]
Hi @nate-meir
I'm not sure how you called the code. Do you want to post (part of) it? Remove any API tokens of course


Did you check out the examples here?
https://github.com/gabrielsroka/OktaAPI.psm1/blob/master/CallOktaAPI.ps1#L168

e.g.:
```powershell
$profile = @{name = "name"; description = "description"}
$group = New-OktaGroup @{profile = $profile}
```

**Comment by gabrielsroka** [comment]
I've also added more examples to the [README.md](/gabrielsroka/OktaAPI.psm1#usage)

**Comment by gabrielsroka** [comment]
Hi @nate-meir

Let me know if my code solves your issue.

**Comment by jamesnelsonaristocratdotcom** [comment]
For what it's worth, this still doesn't work for me.  I"m familiar with the profile construct from creating users, but I get a 400 error no matter what I do when creating a group.

**Comment by gabrielsroka** [comment]
can u share your code? does the 400 mean another group already exists?

**Comment by gabrielsroka** [comment]
eg, this works in PowerShell 5. which vesion are you using?

```pwsh
try {
  New-OktaGroup @{profile = @{name = 'G'}}
} catch  {
  get-error $_
}
```

```
errorSummary : Api validation failed: name
errorCauses  : {@{errorSummary=name: An object with this field already exists in the current organization}}
...
```

in PowerShell 7

```pwsh
New-OktaGroup @{profile = @{name = 'G'}}
```

```
{"errorSummary": "Api validation failed: name",  
"errorCauses": [{ "errorSummary": "name: An object with this field already exists in the current organization"}]}
...
```

**Comment by jamesnelsonaristocratdotcom** [comment]
i actually figured out what the problem was...there was a custom attribute on our groups with a mandatory flag --  once i specified a value for that attribute in my script, it worked just fine.  Sorry for the false alarm!
