### ISSUE TITLE
Invoke-Webrequest fails on powershell 5 and below on a machine without IE or a user that has never run it

### ISSUE THREAD

**Issue by spencerryan** [gabrielsroka/OktaAPI.psm1#8]
When running Invoke-WebRequest on powershell < 6 the cmdlet will fail if Internet Explorer is not available (such as in core versions of windows) or if the user running the code has never opened IE at least once and clicked through the initial setup. The error given is:

```
    The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
```
This means that when running as a scheduled task the specific user running the task would have to interactively log into that machine and run IE at least once. This is not ideal. 

Per Microsoft, "UseBasicParsing" has become the default in PS6, however even new installs of server 2019 don't have PS6. (https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7)

There is no functionality loss for this use case (UseBasicParsing disables DOM parsing). 

I'll submit a pull request shortly with some updated code.

**Comment by gabrielsroka** [comment]
Hi @spencerryan ,

Thanks for the issue and the PR. I was just having issues with the parsing in PoSh 6 (but not this issue).

I made the change, but I used the same space (not tab) and brace style as the rest of the source :)

- Gabriel

**Comment by spencerryan** [comment]
Ah good catch! My editor abstracts it and I forgot to check.
